---
- hosts: all
  become: true
  tasks:
    - name: debug var inventory_hostname
      debug: var=inventory_hostname
    - name: debug var ansible_hostname
      debug: var=ansible_hostname
    - name: debug var jenkins_common_role_username
      debug: var=jenkins_common_role_username
    - name: debug var jenkins_common_role_override_username
      debug: var=jenkins_common_role_override_username
    - name: debug var jenkins_yum_packages_regular
      debug: var=jenkins_yum_packages_regular
    - name: debug var jenkins_yum_packages_system
      debug: var=jenkins_yum_packages_system
