---
- hosts: all
  become: true
  tasks:
    - name: debug var inventory_hostname
      debug: var=inventory_hostname
    - name: debug var ansible_hostname
      debug: var=ansible_hostname
    - name: debug var jenkins_common_role_username
      debug: var=jenkins_common_role_username
    - name: debug var jenkins_common_role_override_username
      debug: var=jenkins_common_role_override_username
    - name: debug var jenkins_yum_packages_regular
      debug: var=jenkins_yum_packages_regular
    - name: debug var jenkins_yum_packages_system
      debug: var=jenkins_yum_packages_system

    - name: Get list of yum repositories
      shell: ls -lh /etc/yum.repos.d/*
      register: debug1
      failed_when: false
    - name: Show list of yum repositories
      debug: var=debug1
      failed_when: false

    - name: Get list of gpg keys used by rpm (before yum install)
      shell: ls -lh /etc/pki/rpm-gpg/*
      register: debug2
      failed_when: false
    - name: Show list of gpg keys
      debug: var=debug2
      failed_when: false

    - name: Get yum yarn depository information
      shell: cat /etc/yum.repos.d/yarn.repo
      register: debug3
      failed_when: false
    - name: Show yum yarn depository information
      debug: var=debug3
      failed_when: false

    - name: Disable GPG keys on cabelo repos as key is currently broken
      shell: sed -i -e 's!gpgcheck = 1!gpgcheck = 0!g' /etc/yum.repos.d/cabelo.repo
      failed_when: false
      when: False

    - name: Get yum cabelo depository information
      shell: cat /etc/yum.repos.d/cabelo.repo
      register: debug4
      failed_when: false
    - name: Show yum cabelo depository information
      debug: var=debug4
      failed_when: false

    - name: Attempt to install yarn manually for debugging
      shell: yum -y --enablerepo=='*' install yarn maven jq owasp-zap
      register: debug5
      failed_when: false
      when: False
    - name: Show what happened with the attempt to install packages via yum
      debug: var=debug5
      failed_when: false
      when: False

    - name: Get list of gpg keys used by rpm (after yum install)
      shell: ls -lh /etc/pki/rpm-gpg/*
      register: debug6
      failed_when: false
    - name: Show list of gpg keys
      debug: var=debug6
      failed_when: false
